import { describe, expect, test } from "bun:test";
import {
  DIAGNOSE_SPEC,
  doorModePlatformError,
  executeDiagnoseCommand,
  renderDiagnoseHelp,
  type DiagnoseCommandContext,
} from "../src/commands/diagnose.ts";
import {
  isDoorTaskAction,
  parseServeLine,
  type DoorListenerRow,
  type DoorProcessRow,
  type DoorSystemSnapshot,
  type DoorTaskRow,
} from "../src/capabilities/door-health.ts";

// ---------------------------------------------------------------------------
// Fixtures: a two-door host shaped like the field provider (desktop-60026li):
// ukp-door uses the template's literal %USERPROFILE% argument, the renamed
// second door an absolute path; plus noise tasks that must NOT match.
// ---------------------------------------------------------------------------

const HOME = "C:\\Users\\fixture";

const VBS_MAIN = `${HOME}\\.ukp\\start-door-hidden.vbs`;
const CMD_MAIN = `${HOME}\\.ukp\\start-door.cmd`;
const LOG_MAIN = `${HOME}\\.ukp\\door.log`;
const VBS_SECOND = `${HOME}\\.ukp\\start-agent-eval-hidden.vbs`;
const CMD_SECOND = `${HOME}\\.ukp\\start-agent-eval.cmd`;
const LOG_SECOND = `${HOME}\\.ukp\\door-agent-eval.log`;

const SECRET = "tok-do-not-print-0123456789abcdef";

const CMD_MAIN_TEXT = [
  "@echo off",
  "rem UKP resident door (generated by ukp serve --print-task)",
  `set "UKP_SERVE_TOKEN=${SECRET}"`,
  `   ukp serve --endpoint skill-dev --host 0.0.0.0 --port 8570 --tls`,
].join("\r\n");

const VBS_MAIN_TEXT = [
  "' UKP door hidden launcher",
  "Dim cmdline : cmdline = \"cmd /c \" & q & q & home & \"\\.ukp\\start-door.cmd\" & q & \" >> \" & q & home & \"\\.ukp\\door.log\" & q & \" 2>&1\" & q",
].join("\r\n");

const LOG_MAIN_TEXT = [
  "serving endpoint 'skill-dev' (ukp-remote v1)",
  "  listening: https://0.0.0.0:8570",
  "  auth: bearer token required",
  "  tls: self-signed identity (persisted) sha256/EXAMPLE (SAN: DNS:localhost)",
].join("\r\n");

const CMD_SECOND_TEXT = [
  "@echo off",
  `set "UKP_SERVE_TOKEN=${SECRET}"`,
  `ukp serve --endpoint agent-eval --host 0.0.0.0 --port 8571 --tls`,
].join("\r\n");

const VBS_SECOND_TEXT = VBS_MAIN_TEXT
  .replaceAll("start-door.cmd", "start-agent-eval.cmd")
  .replaceAll("\\.ukp\\door.log", "\\.ukp\\door-agent-eval.log");

const LOG_SECOND_TEXT = [
  "serving endpoint 'agent-eval' (ukp-remote v1)",
  "  listening: https://0.0.0.0:8571",
  "  tls: self-signed identity (generated) sha256/EXAMPLE2 (SAN: DNS:localhost)",
].join("\r\n");

function baseFiles(): Map<string, string> {
  return new Map<string, string>([
    [VBS_MAIN, VBS_MAIN_TEXT],
    [CMD_MAIN, CMD_MAIN_TEXT],
    [LOG_MAIN, LOG_MAIN_TEXT],
    [VBS_SECOND, VBS_SECOND_TEXT],
    [CMD_SECOND, CMD_SECOND_TEXT],
    [LOG_SECOND, LOG_SECOND_TEXT],
  ]);
}

function healthySnapshot(): DoorSystemSnapshot {
  return {
    tasks: [
      {
        name: "ukp-door",
        state: "Running",
        execute: "wscript.exe",
        arguments: `"%USERPROFILE%\\.ukp\\start-door-hidden.vbs"`,
      },
      {
        name: "ukp-door-agent-eval",
        state: "Running",
        execute: "wscript.exe",
        arguments: `"${VBS_SECOND}"`,
      },
      { name: "OneDrive Reporting", state: "Running", execute: "notepad.exe", arguments: "" },
      { name: "SomeOtherVbs", state: "Ready", execute: "wscript.exe", arguments: `"C:\\Scripts\\unrelated.vbs"` },
    ],
    processes: [
      {
        pid: 64196,
        ppid: 1,
        name: "wscript.exe",
        commandLine: `"wscript.exe" "${VBS_MAIN}"`,
      },
      {
        pid: 65500,
        ppid: 64196,
        name: "cmd.exe",
        commandLine: `cmd /c ""${CMD_MAIN}" >> "${LOG_MAIN}" 2>&1"`,
      },
      { pid: 43492, ppid: 65500, name: "bun.exe", commandLine: `bun ukp serve --endpoint skill-dev` },
      {
        pid: 40628,
        ppid: 1,
        name: "wscript.exe",
        commandLine: `"wscript.exe" "${VBS_SECOND}"`,
      },
      {
        pid: 67328,
        ppid: 40628,
        name: "cmd.exe",
        commandLine: `cmd /c ""${CMD_SECOND}" >> "${LOG_SECOND}" 2>&1"`,
      },
      { pid: 6616, ppid: 67328, name: "bun.exe", commandLine: `bun ukp serve --endpoint agent-eval` },
    ],
    listeners: [
      { address: "0.0.0.0", port: 8570, pid: 43492 },
      { address: "0.0.0.0", port: 8571, pid: 6616 },
    ],
  };
}

function doorContext(
  snapshot: DoorSystemSnapshot,
  files: Map<string, string> = baseFiles(),
): DiagnoseCommandContext {
  return {
    currentDirectory: HOME,
    registryPath: `${HOME}\\registry.toml`,
    doorProbe: () => snapshot,
    readTextFile: (path) => {
      const content = files.get(path);
      if (content === undefined) throw new Error(`ENOENT: ${path}`);
      return content;
    },
    homeDir: HOME,
  };
}

describe("diagnose --door", () => {
  test("healthy dual doors: both reported ok, exit 0, token never echoed", () => {
    const result = executeDiagnoseCommand(["--door"], doorContext(healthySnapshot()));
    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");
    const out = result.stdout;
    // Both doors found, sorted by task name; noise tasks excluded.
    expect(out).toContain("== door: ukp-door ==");
    expect(out).toContain("== door: ukp-door-agent-eval ==");
    expect(out.indexOf("== door: ukp-door-agent-eval ==")).toBeGreaterThan(out.indexOf("== door: ukp-door =="));
    expect(out).not.toContain("OneDrive");
    expect(out).not.toContain("unrelated");
    // The %USERPROFILE% task argument resolved and matched the live wscript.
    expect(out).toContain(`launcher: ${VBS_MAIN}`);
    expect(out).toContain("tree: wscript(64196) > cmd(65500) > bun(43492)");
    expect(out).toContain("port: 8570 listening (pid 43492, inside the door tree)");
    expect(out).toContain("port: 8571 listening (pid 6616, inside the door tree)");
    expect(out).toContain(`log: ${LOG_MAIN}`);
    expect(out).toContain("log_tail: banner present (last: listening: https://0.0.0.0:8570)");
    expect(out).toContain("serve: endpoint skill-dev, host 0.0.0.0, port 8570");
    expect(out).toContain("status: ok");
    expect(out).not.toContain("status: warning");
    // Secret-free: the start script was read (serve line parsed) but its
    // token line never reaches the output (D-090 convention).
    expect(out).not.toContain(SECRET);
    expect(out).not.toContain("UKP_SERVE_TOKEN");
  });

  test("stopped door (task Ready, no tree, port free): warning + exit 1", () => {
    const snapshot = healthySnapshot();
    snapshot.tasks = snapshot.tasks.filter((task) => task.name !== "ukp-door-agent-eval");
    snapshot.tasks[0]!.state = "Ready";
    snapshot.processes = [];
    snapshot.listeners = [];
    const result = executeDiagnoseCommand(["--door"], doorContext(snapshot));
    expect(result.exitCode).toBe(1);
    const out = result.stdout;
    expect(out).toContain("== door: ukp-door ==");
    expect(out).toContain("task: Ready");
    expect(out).toContain("tree: (no launcher process)");
    expect(out).toContain("port: 8570 free (nothing listens)");
    expect(out).toContain("door not running");
    expect(out).toContain("Start-ScheduledTask -TaskName ukp-door");
    expect(out).toContain("status: warning");
  });

  test("task says Running but the tree is gone: its own wording", () => {
    const snapshot = healthySnapshot();
    snapshot.processes = [];
    snapshot.listeners = [];
    const result = executeDiagnoseCommand(["--door"], doorContext(snapshot));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("no launcher process exists");
    expect(result.stdout).toContain("crashed past the launcher's bounded retries");
  });

  test("port held by an outside process: names the holder", () => {
    const snapshot = healthySnapshot();
    snapshot.processes = snapshot.processes.filter((proc) => proc.pid !== 40628 && proc.pid !== 67328 && proc.pid !== 6616);
    snapshot.processes.push({ pid: 9999, ppid: 1, name: "bun.exe", commandLine: "bun ukp serve --port 8571 (leftover)" });
    snapshot.listeners = snapshot.listeners.filter((entry) => entry.port !== 8571);
    snapshot.listeners.push({ address: "0.0.0.0", port: 8571, pid: 9999 });
    const result = executeDiagnoseCommand(["--door"], doorContext(snapshot));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("port: 8571 listening (pid 9999, OUTSIDE the door tree)");
    expect(result.stdout).toContain("bun(9999) OUTSIDE this door's process tree");
    expect(result.stdout).toContain("netstat -ano | findstr :8571");
  });

  test("tree alive but nothing listens: bind-failure wording", () => {
    const snapshot = healthySnapshot();
    snapshot.listeners = [];
    const result = executeDiagnoseCommand(["--door"], doorContext(snapshot));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("tree is alive but nothing listens on port 8570");
  });

  test("door.log tails triage: EADDRINUSE and the double-redirect shape", () => {
    const files = baseFiles();
    files.set(LOG_MAIN, ["Error: listen EADDRINUSE: address already in use", ""].join("\r\n"));
    files.set(
      LOG_SECOND,
      ["The process cannot access the file because it is being used by another process.", ""].join("\r\n"),
    );
    const result = executeDiagnoseCommand(["--door"], doorContext(healthySnapshot(), files));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("door.log tail carries EADDRINUSE");
    expect(result.stdout).toContain("'being used by another process'");
    expect(result.stdout).toContain("double-redirect deadlock shape");
    expect(result.stdout).toContain("'ukp serve --print-task'");
    expect(result.stdout).toContain("no serving banner in the tail");
  });

  test("failure scar lines superseded by a later banner do not warn (latest evidence wins)", () => {
    // The field shape of door 8570: ISSUE-016-era conflict lines at the top,
    // several healthy restart banners after them.
    const files = baseFiles();
    files.set(
      LOG_MAIN,
      [
        "The process cannot access the file because it is being used by another process.",
        "The process cannot access the file because it is being used by another process.",
        LOG_MAIN_TEXT,
      ].join("\r\n"),
    );
    files.set(
      LOG_SECOND,
      [
        "Error: listen EADDRINUSE: address already in use",
        LOG_SECOND_TEXT,
      ].join("\r\n"),
    );
    const result = executeDiagnoseCommand(["--door"], doorContext(healthySnapshot(), files));
    expect(result.exitCode).toBe(0);
    expect(result.stdout).not.toContain("EADDRINUSE");
    expect(result.stdout).not.toContain("being used by another process");
    expect(result.stdout).toContain("status: ok");
  });

  test("missing launcher and start script: tolerance, not a crash", () => {
    const files = baseFiles();
    files.delete(VBS_MAIN);
    files.delete(CMD_MAIN);
    const result = executeDiagnoseCommand(["--door"], doorContext(healthySnapshot(), files));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain(`launcher script not found at ${VBS_MAIN}`);
    expect(result.stdout).toContain(`start script not found at ${CMD_MAIN}`);
  });

  test("start script without a serve line: port cannot be determined", () => {
    const files = baseFiles();
    files.set(CMD_MAIN, ["@echo off", `set "UKP_SERVE_TOKEN=${SECRET}"`].join("\r\n"));
    const result = executeDiagnoseCommand(["--door"], doorContext(healthySnapshot(), files));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("no 'ukp serve' line found");
    expect(result.stdout).toContain("the door's port cannot be determined");
  });

  test("unresolvable task action path: structural failure", () => {
    const snapshot = healthySnapshot();
    snapshot.tasks = snapshot.tasks.slice(0, 1);
    snapshot.tasks[0]!.arguments = `"%SOMEVAR%\\.ukp\\start-door-hidden.vbs"`;
    const result = executeDiagnoseCommand(["--door"], doorContext(snapshot));
    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("could not be resolved to a launcher path");
    expect(result.stdout).toContain("%SOMEVAR%");
    expect(result.stdout).toContain("status: failed");
  });

  test("host with no doors: informational note, exit 0", () => {
    const snapshot: DoorSystemSnapshot = { tasks: [], processes: [], listeners: [] };
    const result = executeDiagnoseCommand(["--door"], doorContext(snapshot));
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("no resident doors found");
    expect(result.stdout).toContain("This is not an error");
  });

  test("probe failure surfaces as an error, not a crash", () => {
    const context: DiagnoseCommandContext = {
      currentDirectory: HOME,
      registryPath: `${HOME}\\registry.toml`,
      doorProbe: () => {
        throw new Error("powershell gone");
      },
      homeDir: HOME,
    };
    const result = executeDiagnoseCommand(["--door"], context);
    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain("ukp diagnose: door snapshot failed: powershell gone");
  });

  test("--door refuses selector combinations and duplicates (usage errors)", () => {
    const context = doorContext(healthySnapshot());
    const withEndpoint = executeDiagnoseCommand(["--door", "--endpoint", "x"], context);
    expect(withEndpoint.exitCode).toBe(2);
    expect(withEndpoint.stderr).toContain("cannot be combined with --endpoint or -g");
    const withGlobal = executeDiagnoseCommand(["--door", "-g"], context);
    expect(withGlobal.exitCode).toBe(2);
    expect(withGlobal.stderr).toContain("cannot be combined with --endpoint or -g");
    const doubled = executeDiagnoseCommand(["--door", "--door"], context);
    expect(doubled.exitCode).toBe(2);
    expect(doubled.stderr).toContain("--door may only be specified once");
  });

  test("help documents the door mode; the Scope section survives", () => {
    const help = renderDiagnoseHelp();
    expect(help).toContain("--door");
    expect(help.replace(/\s+/g, " ")).toContain("Read-only");
    expect(help.replace(/\s+/g, " ")).toContain("validates the current folder as a Service");
    expect(help.replace(/\s+/g, " ")).toContain("cannot be combined with --endpoint");
    expect(help).toContain(DIAGNOSE_SPEC.usage);
  });

  test("platform gate: Windows-only with a Linux pointer", () => {
    expect(doorModePlatformError("linux")).toContain("--door is Windows-only");
    expect(doorModePlatformError("linux")).toContain("systemctl --user status ukp-door.socket");
    expect(doorModePlatformError("darwin")).toContain("Windows-only");
    expect(doorModePlatformError("win32")).toBeUndefined();
  });
});

describe("door task matching and serve parsing (pure)", () => {
  test("door task matching: wscript on a .ukp vbs, rename-tolerant", () => {
    expect(isDoorTaskAction("wscript.exe", `"%USERPROFILE%\\.ukp\\start-door-hidden.vbs"`)).toBe(true);
    expect(isDoorTaskAction("C:\\Windows\\System32\\wscript.exe", `"${VBS_SECOND}"`)).toBe(true);
    expect(isDoorTaskAction("wscript.exe", `"C:\\Scripts\\unrelated.vbs"`)).toBe(false);
    expect(isDoorTaskAction("notepad.exe", `"${VBS_MAIN}"`)).toBe(false);
    expect(isDoorTaskAction("wscript.exe", `"%USERPROFILE%\\.ukp\\start-door.cmd"`)).toBe(false);
  });

  test("serve line parsing picks endpoint/host/port and nothing else", () => {
    const parsed = parseServeLine(CMD_MAIN_TEXT);
    expect(parsed).toEqual({ endpoint: "skill-dev", host: "0.0.0.0", port: 8570 });
    const hostDoor = parseServeLine(["ukp serve --host 127.0.0.1 --port 8579 --allow-anonymous"].join("\r\n"));
    expect(hostDoor).toEqual({ host: "127.0.0.1", port: 8579 });
    expect(parseServeLine("@echo off\r\nrem nothing")).toBeUndefined();
  });
});
